.Dd Oct 5, 2024
.Dt WIIMIX 6
.Os
.Sh NAME
.Nm wiimix
.Nd A fork of the Dolphin emulator designed for shuffling games
.Sh SYNOPSIS
.Nm wiimix
.Op Fl bdhl
.Op Fl a Ar audio
.Op Fl c Ar str
.Op Fl e Ar file
.Op Fl m Ar file
.Op Fl u Ar path
.Op Fl v Ar video
.Sh DESCRIPTION
Wiimix is a fork of the Dolphin emulator designed for shuffling games.
It is currently under development, but intends to extend dolphin to cache multiple games at a time
and switch between them and certain save states for each game. This core functionality will be combined 
with functionality such as game specific objectives and a save state database to implement systems such as 
objective-based randomizers and bingo boards/lockouts, as well as to allow for customizing your own personal wiimix!
.Pp
.Nm
features a graphical user interface made using Qt 5.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl a Ar audio , Fl Fl audio_emulation= Ns Ar audio
Low level
.Pq Sy LLE
or high level
.Pq Sy HLE
audio
.It Fl b , Fl Fl batch
Exit wiimix with emulator
.It Fl c Ar text , Fl Fl confirm= Ns Ar text
Set Confirm on Stop
.It Fl d , Fl Fl debugger
Open the debugger
.It Fl e Ar file , Fl Fl exec= Ns Ar file
Load the specified file
.It Fl h , Fl Fl help
Print a help message
.It Fl l , Fl Fl logger
Open the logger
.Po
.Pa .dol , .elf , .wad , .gcm , .iso
.Pc
.It Fl m Ar file , Fl Fl movie= Ns Ar file
Play a movie file
.It Fl u Ar path , Fl Fl user= Ns Ar path
User folder path
.It Fl v , Fl Fl video_backend= Ns Ar video
OpenGL
.Pq Sy OGL
or
.Sy Software Renderer
video backend
.El
.Sh FILES
.Bl -tag -width Ds
.It Pa $HOME/.dolphin-emu
Default user configuration directory.
.El
.Sh AUTHOR
This manual page was originally written by Jeremy Newton and adapted by Xander Kutulas, but may be distributed freely
using the CC BY license.